<h1 align=center><font size = 8>Battle of Neighborhoods Week -1</font></h1>

#### Background: Delhi, also called as National Capital Territory of Delhi is a cosmopolitan city and union territory of India containing New Delhi, the official capital of India. 

#### Delhi being a second highest populated capital city in the world with dense population, finding a best place for real estate investment, especially for residential plots is a problem to deal with.

## 1. Introduction

<img src = "https://www.lc3.ch/wp-content/uploads/2018/03/delhi.jpg"> </a>

## 2. Business Prob

#### This is a hard nut to break for a commoner who is looking to find an economical area in Delhi to invest in a residential plot and construct a house on the same land. Or to buy an already constructed property based on the age of the property.

#### Apart from the land cost and construction cost per square meter we also wanted to consider the social facilities and services available in the respective areas to add value to our estimated economical cost projected in a given area.

#### Considering all the above factors like land cost, construction cost and facilities available in a given area, the economical areas for investment will be listed.

#### Target Audience:

#### •	Real Estate Business personnel who would like to get an analysis on the estimated costs in a given area to invest on land, construct and sell homes in the market.
#### •	Commoners who would like to get a list of economical areas to invest on residential plots for long term investment.

### Finding Economical areas for investing in residential plots and housing around the districts in Delhi

##### Before we get the data and start exploring it, let's download all the dependencies that we will need.

In [13]:
pip install geopy

Collecting geopy
  Downloading https://files.pythonhosted.org/packages/80/93/d384479da0ead712bdaf697a8399c13a9a89bd856ada5a27d462fb45e47b/geopy-1.20.0-py2.py3-none-any.whl (100kB)
     |████████████████████████████████| 102kB 932kB/s ta 0:00:01
Collecting geographiclib<2,>=1.49 (from geopy)
  Downloading https://files.pythonhosted.org/packages/5b/ac/4f348828091490d77899bc74e92238e2b55c59392f21948f296e94e50e2b/geographiclib-1.49.tar.gz
Building wheels for collected packages: geographiclib
  Building wheel for geographiclib (setup.py) ... done
  Stored in directory: /home/jupyterlab/.cache/pip/wheels/99/45/d1/14954797e2a976083182c2e7da9b4e924509e59b6e5c661061
Successfully built geographiclib
Installing collected packages: geographiclib, geopy
Successfully installed geographiclib-1.49 geopy-1.20.0
Note: you may need to restart the kernel to use updated packages.

In [15]:
import requests
from geopy.geocoders import Nominatim
import pandas as pd
import numpy as np

In [16]:
areas = pd.read_csv("Delhi_Area_by_Category.csv")

## 3. Download and Explore Dataset

##### Datasets are obtained mainly from the following data sources:
https://en.wikipedia.org/wiki/List_of_districts_of_Delhi

https://www.myloancare.in/delhi-circle-rate-revised/

### Approach
#### Step-1: We will use the dataset containing the Delhi Districts and respective areas to get the geo-spatial information.
#### Step-2: After that, the Rate Category data is used to find the rates (Land cost and Construction cost) for the given area to sort out the total cost.
#### Step-3: Now, we will calculate the cost for 200 Sq mtrs and will use the cost to find the economical areas in a given district.

#### Read the data for Delhi Areas and respective category along with District and Pincode information

In [17]:
areas.head(10)

                 Area    Category       District  Pincode
0      Friends Colony  Category A    South Delhi   110025
1          Golf Links  Category A    South Delhi   110003
2  New friends Colony  Category A    South Delhi   110025
3           Lodi Road  Category A    South Delhi   110003
4       Maharani Bagh  Category A    South Delhi   110065
5         Nehru Place  Category A    South Delhi   110019
6     Panchsheel Park  Category A    South Delhi   110017
7      Rajendra Nagar  Category A  Central Delhi   110060
8      Shanti Niketan  Category A    South Delhi   110021
9        Sunder Nagar  Category A    South Delhi   110003

In [18]:
dl_catvs = pd.read_csv("Delhi_Rate_Category_Values.csv")

#### Now let's read the category Master csv file where the categories are mapped to respective rates

In [19]:
dl_catvs.head(10)

     Category  Land Cost sq mtr  Construction Cost sq mtr
0  Category A            774000                     21960
1  Category B            246000                     17400
2  Category C            160000                     13920
3  Category D            128000                     11160
4  Category E             70080                      9360
5  Category F             56640                      8220
6  Category G             46200                      6960
7  Category H             23280                      3480

In [20]:
geolocator = Nominatim()
areas['Area_geospat']= areas['Pincode'].apply(geolocator.geocode).apply(lambda x: (x.latitude, x.longitude))

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Using Nominatim with the default "geopy/1.20.0" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.
  """Entry point for launching an IPython kernel.

#### Let's get the coordinates of all the areas

In [23]:
pd.set_option('display.max_rows', 500)
areas.loc[areas['Area'] == 'Golf Links', 'Area_geospat'] = '(28.5948, 77.2262)'
areas.loc[areas['Area'] == 'Sunder Nagar', 'Area_geospat'] = '(28.6017, 77.2434)'
areas.loc[areas['Area'] == 'Defence Colony', 'Area_geospat'] = '(28.5734, 77.2326)'
areas.loc[areas['Area'] == 'East Patel Nagar', 'Area_geospat'] = '(28.6468, 77.1721)'
areas.loc[areas['Area'] == 'Lajpat Nagar', 'Area_geospat'] = '(28.5649, 77.2403)'
areas.loc[areas['Area'] == 'Jasola Vihar', 'Area_geospat'] = '(28.5470, 77.2894)'
areas.loc[areas['Area'] == 'Kirti Nagar', 'Area_geospat'] = '(28.6494, 77.1437)'
areas.loc[areas['Area'] == 'Daryaganj', 'Area_geospat'] = '(28.6448, 77.2404)'
areas.loc[areas['Area'] == 'East End Enclave', 'Area_geospat'] = '(28.6428, 77.2806)'
areas.loc[areas['Area'] == 'Moti Nagar', 'Area_geospat'] = '(28.6623, 77.1411)'
areas.loc[areas['Area'] == 'Okhla', 'Area_geospat'] = '(28.5626, 77.2914)'
areas.loc[areas['Area'] == 'Ambedkar Colony', 'Area_geospat'] = '(28.5351, 77.0566)'
areas.loc[areas['Area'] == 'Hari Nagar Extension', 'Area_geospat'] = '(28.6249, 77.1109)'
areas.loc[areas['Area'] == 'Sultanpur Majra', 'Area_geospat'] = '(28.6959, 77.0805)'
areas.loc[areas['Area'] == 'Lodi Road', 'Area_geospat'] = '(28.5948, 77.2262)'
areas

,Area,Category,District,Pincode,Area_geospat
0,Friends Colony,Category A,South Delhi,110025,"(28.5549863537844, 77.2850594047551)"
1,Golf Links,Category A,South Delhi,110003,"(28.5948, 77.2262)"
2,New friends Colony,Category A,South Delhi,110025,"(28.5549863537844, 77.2850594047551)"
3,Lodi Road,Category A,South Delhi,110003,"(28.5948, 77.2262)"
4,Maharani Bagh,Category A,South Delhi,110065,"(28.5666050850646, 77.260266757841)"
5,Nehru Place,Category A,South Delhi,110019,"(28.5412625875572, 77.2555294508654)"
6,Panchsheel Park,Category A,South Delhi,110017,"(28.5505882082073, 77.2118463446042)"
7,Rajendra Nagar,Category A,Central Delhi,110060,"(28.6365498513564, 77.1810625919087)"
8,Shanti Niketan,Category A,South Delhi,110021,"(28.5943102856607, 77.1832613749184)"
9,Sunder Nagar,Category A,South Delhi,110003,"(28.6017, 77.2434)"
10,Vasant Vihar,Category A,New Delhi,110057,"(28.5664859558122, 77.1606676817168)"
11,Anand Niketan,Category A,South West Delhi,110021,"(28.5943102856607, 77.1832613749184)"
12,Bhikaji Cama Place,Category A,South West Delhi,110029,"(28.5665088297742, 77.2049494522477)"
13,Sarvapriya Vihar,Category B,South Delhi,110016,"(28.5492326225742, 77.198788933341)"
14,Sarvodaya Enclave,Category B,South Delhi,110017,"(28.5505882082073, 77.2118463446042)"
15,Anand Lok,Category B,South Delhi,110049,"(28.5573308642989, 77.2216932240043)"
16,Andrews Ganj,Category B,South Delhi,110049,"(28.5573308642989, 77.2216932240043)"
17,Defence Colony,Category B,South Delhi,110024,"(28.5734, 77.2326)"
18,Greater Kailash 1,Category B,South Delhi,110048,"(28.5435926583801, 77.2394966857338)"
19,Greater Kailash 2,Category B,South Delhi,110048,"(28.5435926583801, 77.2394966857338)"
20,Greater Kailash 3,Category B,South Delhi,110048,"(28.5435926583801, 77.2394966857338)"
21,Greater Kailash 4,Category B,South Delhi,110048,"(28.5435926583801, 77.2394966857338)"
22,Green Park,Category B,South West Delhi,110016,"(28.5492326225742, 77.198788933341)"
23,Gulmohar Park,Category B,South Delhi,110049,"(28.5573308642989, 77.2216932240043)"
24,Hamdard Nagar,Category B,South Delhi,110062,"(28.5133831666667, 77.2320357666667)"
25,Hauz Khas,Category B,South West Delhi,110016,"(28.5492326225742, 77.198788933341)"
26,Maurice Nagar,Category B,North Delhi,110007,"(28.6840249522853, 77.2091293990836)"
27,Munirka Vihar,Category B,South West Delhi,110067,"(28.5440606659543, 77.1695805977495)"
28,Neeti Bagh,Category B,South Delhi,110049,"(28.5573308642989, 77.2216932240043)"
29,Nehru Enclave,Category B,South Delhi,110019,"(28.5412625875572, 77.2555294508654)"
30,Nizamuddin East,Category B,South East Delhi,110013,"(28.5866396, 77.2523949)"
31,Panchsheel Park,Category B,North East Delhi,110017,"(28.5505882082073, 77.2118463446042)"
32,Safdarjang Enclave,Category B,South West Delhi,110029,"(28.5665088297742, 77.2049494522477)"
33,Alaknanda,Category C,South Delhi,110019,"(28.5412625875572, 77.2555294508654)"
34,Chittaranjan Park,Category C,South Delhi,110019,"(28.5412625875572, 77.2555294508654)"
35,Civil Lines,Category C,North Delhi,110054,"(28.6826815226524, 77.2208834697677)"
36,East of Kailash,Category C,South Delhi,110065,"(28.5666050850646, 77.260266757841)"
37,East Patel Nagar,Category C,Central Delhi,110008,"(28.6468, 77.1721)"
38,Jhandewalan Area,Category C,Central Delhi,110055,"(28.6430821225399, 77.212860946403)"
39,Kalkaji,Category C,South Delhi,110019,"(28.5412625875572, 77.2555294508654)"
40,Lajpat Nagar,Category C,South Delhi,110024,"(28.5649, 77.2403)"
41,Malviya Nagar,Category C,South Delhi,110017,"(28.5505882082073, 77.2118463446042)"
42,Munirka,Category C,South West Delhi,110067,"(28.5440606659543, 77.1695805977495)"
43,Nizamuddin West,Category C,South Delhi,110013,"(28.5866396, 77.2523949)"
44,Panchsheel Extension,Category C,South Delhi,110017,"(28.5505882082073, 77.2118463446042)"
45,Punjabi Bagh,Category C,West Delhi,110026,"(28.632280025, 77.15354095)"
46,Som Vihar,Category C,South West Delhi,110022,"(28.5700935843653, 77.1689385796648)"
47,Vasant Kunj,Category C,South West Delhi,110070,"(28.5221215326383, 77.1576831367831)"
48,Jasola Vihar,Category D,North East Delhi,110020,"(28.5470, 77.2894)"
49,Karol Bagh,Category D,Central Delhi,110005,"(28.6497299241131, 77.1908485880597)"
50,Kirti Nagar,Category D,West Delhi,110015,"(28.6494, 77.1437)"
51,Mayur Vihar,Category D,East Delhi,110096,"(28.6037843008016, 77.3236022975316)"
52,New Rajinder Nagar,Category D,Central Delhi,110060,"(28.6365498513564, 77.1810625919087)"
53,Old Rajinder Nagar,Category D,Central Delhi,110060,"(28.6365498513564, 77.1810625919087)"
54,Rajouri Garden,Category D,West Delhi,110027,"(28.6487573405607, 77.1191334141089)"
55,Anand Vihar,Category D,East Delhi,110092,"(28.6301629, 77.2775133)"
56,Daryaganj,Category D,Central Delhi,110002,"(28.6448, 77.2404)"
57,Dwarka,Category D,South West Delhi,110075,"(28.5919444408102, 77.0593207689518)"
58,Gagan Vihar,Category D,East Delhi,110092,"(28.6301629, 77.2775133)"
59,Hudson Line,Category D,North West Delhi,110009,"(28.70575085, 77.2137069451824)"
60,Indraprastha Extension,Category D,North East Delhi,110092,"(28.6301629, 77.2775133)"
61,Janakpuri,Category D,West Delhi,110058,"(28.6211407450149, 77.0842560151698)"
62,Jangpura A,Category D,South Delhi,110014,"(28.580877455835, 77.2553466458054)"
63,Jangpura Extension,Category D,South Delhi,110014,"(28.580877455835, 77.2553466458054)"
64,Chandni Chowk,Category E,North Delhi,110006,"(28.65598435, 77.2316234092723)"
65,East End Enclave,Category E,East Delhi,110031,"(28.6428, 77.2806)"
66,Gagan Vihar Extension,Category E,East Delhi,110092,"(28.6301629, 77.2775133)"
67,Hauz Qazi,Category E,Central Delhi,110006,"(28.65598435, 77.2316234092723)"
68,Jama Masjid,Category E,Central Delhi,110006,"(28.65598435, 77.2316234092723)"
69,Kashmiri Gate,Category E,Central Delhi,110006,"(28.65598435, 77.2316234092723)"
70,Khirki Extension,Category E,South Delhi,110017,"(28.5505882082073, 77.2118463446042)"
71,Madhuban Enclave,Category E,East Delhi,110092,"(28.6301629, 77.2775133)"
72,Mahavir Nagar,Category E,West Delhi,110018,"(28.6338964119353, 77.0820948893626)"
73,Moti Nagar,Category E,New Delhi,110015,"(28.6623, 77.1411)"
74,Paharganj,Category E,Central Delhi,110055,"(28.6430821225399, 77.212860946403)"
75,Pandav Nagar,Category E,East Delhi,110092,"(28.6301629, 77.2775133)"
76,Rohini,Category E,North West Delhi,110085,"(28.71056, 77.1213971)"
77,Sarai Rohilla,Category E,North West Delhi,110035,"(28.6837737044617, 77.1597079578845)"
78,Majnu Ka Tila,Category F,North Delhi,110054,"(28.6826815226524, 77.2208834697677)"
79,Mukherjee Park Extension,Category F,West Delhi,110018,"(28.6338964119353, 77.0820948893626)"
80,Nand Nagri,Category F,North East Delhi,110093,"(28.6983077733379, 77.2999210236626)"
81,Uttam Nagar,Category F,West Delhi,110059,"(28.6270604666667, 77.053891)"
82,Okhla,Category F,South East Delhi,110020,"(28.5626, 77.2914)"
83,Anand Parbat,Category F,Central Delhi,110005,"(28.6497299241131, 77.1908485880597)"
84,Arjun Nagar,Category F,South West Delhi,110029,"(28.5665088297742, 77.2049494522477)"
85,Daya Basti,Category F,North West Delhi,110035,"(28.6837737044617, 77.1597079578845)"
86,Dilshad Garden,Category F,East Delhi,110095,"(28.6625757172355, 77.3010402051657)"
87,Ambedkar Colony,Category F,South West Delhi,110061,"(28.5351, 77.0566)"
88,Ganesh Nagar,Category F,East Delhi,110091,"(28.6032515550225, 77.2993149452696)"
89,Govindpuri,Category F,South Delhi,110019,"(28.5412625875572, 77.2555294508654)"
90,Hari Nagar,Category F,West Delhi,110064,"(28.6297678479076, 77.1089833480347)"
91,Jangpura B,Category F,South Delhi,110014,"(28.580877455835, 77.2553466458054)"
92,Madhu Vihar,Category F,West Delhi,110092,"(28.6301629, 77.2775133)"
93,Ambedkar Nagar Jahangirpuri,Category G,North West Delhi,110033,"(28.7103477069725, 77.1768234916251)"
94,Amdedkar Nagar East Delhi,Category G,East Delhi,110094,"(28.7274959, 77.2626591)"
95,Dabri Extension,Category G,South West Delhi,110045,"(28.5909171469249, 77.0820802604129)"
96,Dakshinpuri,Category G,South Delhi,110062,"(28.5133831666667, 77.2320357666667)"
97,Dashrath Puri,Category G,South West Delhi,110045,"(28.5909171469249, 77.0820802604129)"
98,Hari Nagar Extension,Category G,South Delhi,110044,"(28.6249, 77.1109)"
99,Vivek Vihar,Category G,East Delhi,110095,"(28.6625757172355, 77.3010402051657)"
100,Tagore Garden,Category G,West Delhi,110027,"(28.6487573405607, 77.1191334141089)"
101,Sultanpur Majra,Category H,North West Delhi,110083,"(28.6959, 77.0805)"

In [22]:
areas.head(10)

,Area,Category,District,Pincode,Area_geospat
0,Friends Colony,Category A,South Delhi,110025,"(28.5549863537844, 77.2850594047551)"
1,Golf Links,Category A,South Delhi,110003,"(53.2268541578433, 63.6185934995523)"
2,New friends Colony,Category A,South Delhi,110025,"(28.5549863537844, 77.2850594047551)"
3,Lodi Road,Category A,South Delhi,110003,"(53.2268541578433, 63.6185934995523)"
4,Maharani Bagh,Category A,South Delhi,110065,"(28.5666050850646, 77.260266757841)"
5,Nehru Place,Category A,South Delhi,110019,"(28.5412625875572, 77.2555294508654)"
6,Panchsheel Park,Category A,South Delhi,110017,"(28.5505882082073, 77.2118463446042)"
7,Rajendra Nagar,Category A,Central Delhi,110060,"(28.6365498513564, 77.1810625919087)"
8,Shanti Niketan,Category A,South Delhi,110021,"(28.5943102856607, 77.1832613749184)"
9,Sunder Nagar,Category A,South Delhi,110003,"(53.2268541578433, 63.6185934995523)"

#### After thoroughly reviweing the dataframe, there are few rows with issues having wrong coordinates, we are going to update them using the information from Google.

In [26]:
print(areas.dtypes)

Area            object
Category        object
District        object
Pincode          int64
Area_geospat    object
dtype: object

#### Let's examine the datatypes of all the columns

In [24]:
areas[['Area', 'Category', 'District', 'Area_geospat']] = areas[['Area', 'Category', 'District', 'Area_geospat']].astype(str)
print(areas.dtypes)

Area            object
Category        object
District        object
Pincode          int64
Area_geospat    object
dtype: object

#### We will convert the required string columns to string format

In [25]:
areas[['Longitude','Latitude']] = areas.Area_geospat.str.split(",",expand=True,)
areas.head(10)

,Area,Category,District,Pincode,Area_geospat,Longitude,Latitude
0,Friends Colony,Category A,South Delhi,110025,"(28.5549863537844, 77.2850594047551)",(28.5549863537844,77.2850594047551)
1,Golf Links,Category A,South Delhi,110003,"(28.5948, 77.2262)",(28.5948,77.2262)
2,New friends Colony,Category A,South Delhi,110025,"(28.5549863537844, 77.2850594047551)",(28.5549863537844,77.2850594047551)
3,Lodi Road,Category A,South Delhi,110003,"(28.5948, 77.2262)",(28.5948,77.2262)
4,Maharani Bagh,Category A,South Delhi,110065,"(28.5666050850646, 77.260266757841)",(28.5666050850646,77.260266757841)
5,Nehru Place,Category A,South Delhi,110019,"(28.5412625875572, 77.2555294508654)",(28.5412625875572,77.2555294508654)
6,Panchsheel Park,Category A,South Delhi,110017,"(28.5505882082073, 77.2118463446042)",(28.5505882082073,77.2118463446042)
7,Rajendra Nagar,Category A,Central Delhi,110060,"(28.6365498513564, 77.1810625919087)",(28.6365498513564,77.1810625919087)
8,Shanti Niketan,Category A,South Delhi,110021,"(28.5943102856607, 77.1832613749184)",(28.5943102856607,77.1832613749184)
9,Sunder Nagar,Category A,South Delhi,110003,"(28.6017, 77.2434)",(28.6017,77.2434)

#### Now we will split the coordinates into two new columns Latitude and Longitude by using Pandas String split

In [26]:
areas[['Longitude', 'Latitude']] = areas[['Longitude', 'Latitude']].astype(str)
print(areas.dtypes)

Area            object
Category        object
District        object
Pincode          int64
Area_geospat    object
Longitude       object
Latitude        object
dtype: object

#### Let's convert the new columns to String type to perform string operations

In [27]:
areas['Longitude'] = areas['Longitude'].map(lambda x: str(x).lstrip('(')).astype(str)
areas['Latitude'] = areas['Latitude'].map(lambda x: str(x).rstrip(')')).astype(str)
areas.head(10)

,Area,Category,District,Pincode,Area_geospat,Longitude,Latitude
0,Friends Colony,Category A,South Delhi,110025,"(28.5549863537844, 77.2850594047551)",28.5549863537844,77.2850594047551
1,Golf Links,Category A,South Delhi,110003,"(28.5948, 77.2262)",28.5948,77.2262
2,New friends Colony,Category A,South Delhi,110025,"(28.5549863537844, 77.2850594047551)",28.5549863537844,77.2850594047551
3,Lodi Road,Category A,South Delhi,110003,"(28.5948, 77.2262)",28.5948,77.2262
4,Maharani Bagh,Category A,South Delhi,110065,"(28.5666050850646, 77.260266757841)",28.5666050850646,77.260266757841
5,Nehru Place,Category A,South Delhi,110019,"(28.5412625875572, 77.2555294508654)",28.5412625875572,77.2555294508654
6,Panchsheel Park,Category A,South Delhi,110017,"(28.5505882082073, 77.2118463446042)",28.5505882082073,77.2118463446042
7,Rajendra Nagar,Category A,Central Delhi,110060,"(28.6365498513564, 77.1810625919087)",28.6365498513564,77.1810625919087
8,Shanti Niketan,Category A,South Delhi,110021,"(28.5943102856607, 77.1832613749184)",28.5943102856607,77.1832613749184
9,Sunder Nagar,Category A,South Delhi,110003,"(28.6017, 77.2434)",28.6017,77.2434

#### Now, we will strip-off the left and right braces for Longitude and Latitude respectively using the string functions

In [28]:
areas[['Longitude', 'Latitude']] = areas[['Longitude', 'Latitude']].astype(float)
print(areas.dtypes)

Area             object
Category         object
District         object
Pincode           int64
Area_geospat     object
Longitude       float64
Latitude        float64
dtype: object

#### Now we will convert the Latitude and Longitude to Float type to perform further operations.

In [39]:
dl_catvs.columns = ['Category', 'Land_Cost_sq_mtr', 'Construction_Cost_sq_mtr']
print(dl_catvs.dtypes)

Category                    object
Land_Cost_sq_mtr             int64
Construction_Cost_sq_mtr     int64
dtype: object

#### We will examine the data types for Category master dataframe

#### Now, we can proceed further to join both the dataframes on Category (Key) column. And to meet our data needs, inner join is okay

In [40]:
Acost = pd.merge(areas, dl_catvs, how='inner', on = 'Category')
print(Acost.shape)
print('The dataframe has {} Districts and {} Areas.'.format(
        len(Acost['District'].unique()),
        Acost.shape[0]
    )
)
Acost.head(10)

(102, 9)
The dataframe has 10 Districts and 102 Areas.

,Area,Category,District,Pincode,Area_geospat,Longitude,Latitude,Land_Cost_sq_mtr,Construction_Cost_sq_mtr
0,Friends Colony,Category A,South Delhi,110025,"(28.5549863537844, 77.2850594047551)",28.554986,77.285059,774000,21960
1,Golf Links,Category A,South Delhi,110003,"(28.5948, 77.2262)",28.594800,77.226200,774000,21960
2,New friends Colony,Category A,South Delhi,110025,"(28.5549863537844, 77.2850594047551)",28.554986,77.285059,774000,21960
3,Lodi Road,Category A,South Delhi,110003,"(28.5948, 77.2262)",28.594800,77.226200,774000,21960
4,Maharani Bagh,Category A,South Delhi,110065,"(28.5666050850646, 77.260266757841)",28.566605,77.260267,774000,21960
5,Nehru Place,Category A,South Delhi,110019,"(28.5412625875572, 77.2555294508654)",28.541263,77.255529,774000,21960
6,Panchsheel Park,Category A,South Delhi,110017,"(28.5505882082073, 77.2118463446042)",28.550588,77.211846,774000,21960
7,Rajendra Nagar,Category A,Central Delhi,110060,"(28.6365498513564, 77.1810625919087)",28.636550,77.181063,774000,21960
8,Shanti Niketan,Category A,South Delhi,110021,"(28.5943102856607, 77.1832613749184)",28.594310,77.183261,774000,21960
9,Sunder Nagar,Category A,South Delhi,110003,"(28.6017, 77.2434)",28.601700,77.243400,774000,21960

#### We will calculate the total average cost for 200 sq mtrs in a given area based on the categorical cost values

In [42]:
Acost['Cost for 200 sq mtrs'] = (Acost.Land_Cost_sq_mtr * 200) + (Acost.Construction_Cost_sq_mtr * 150)
Acost.head(10)

,Area,Category,District,Pincode,Area_geospat,Longitude,Latitude,Land_Cost_sq_mtr,Construction_Cost_sq_mtr,Cost for 200 sq mtrs
0,Friends Colony,Category A,South Delhi,110025,"(28.5549863537844, 77.2850594047551)",28.554986,77.285059,774000,21960,158094000
1,Golf Links,Category A,South Delhi,110003,"(28.5948, 77.2262)",28.594800,77.226200,774000,21960,158094000
2,New friends Colony,Category A,South Delhi,110025,"(28.5549863537844, 77.2850594047551)",28.554986,77.285059,774000,21960,158094000
3,Lodi Road,Category A,South Delhi,110003,"(28.5948, 77.2262)",28.594800,77.226200,774000,21960,158094000
4,Maharani Bagh,Category A,South Delhi,110065,"(28.5666050850646, 77.260266757841)",28.566605,77.260267,774000,21960,158094000
5,Nehru Place,Category A,South Delhi,110019,"(28.5412625875572, 77.2555294508654)",28.541263,77.255529,774000,21960,158094000
6,Panchsheel Park,Category A,South Delhi,110017,"(28.5505882082073, 77.2118463446042)",28.550588,77.211846,774000,21960,158094000
7,Rajendra Nagar,Category A,Central Delhi,110060,"(28.6365498513564, 77.1810625919087)",28.636550,77.181063,774000,21960,158094000
8,Shanti Niketan,Category A,South Delhi,110021,"(28.5943102856607, 77.1832613749184)",28.594310,77.183261,774000,21960,158094000
9,Sunder Nagar,Category A,South Delhi,110003,"(28.6017, 77.2434)",28.601700,77.243400,774000,21960,158094000

#### Now that we have all the available data required for Analysis, Visualization and Results.
#### We will use this data for Data analysis, Visualization and Battle of neighborhoods